--- # AMI copy example
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Copy AMI from one regions to anoterr
    ec2_ami_copy:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_regions }}"
      source_region: "{{ aws_regions }}"
      region: us-east-1
      source_image_id: ami-31a7e05e
      wait: no
      name: useastami1
      tags:
        Name:  Nexus
        Service: MyNexus1
    register: instance
