--- # EC2 - start/stop/Terminte module use case
-  hosts: localhost
   connection: local
   remote_user: ansible
   become: yes
   gather_facts: no
   vars_files:
   - files/awscreds.yml
   tasks:
   - name: Manager state
     ec2:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_regions }}"
       instance_ids: i-099a2718153bc1373
       state: running
