--- # EC2 AMI creation from another instance
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks: 
  - name: Get Custom AMI
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_regions }}"
      instance_id: i-099a2718153bc1373
      wait: no
      name: mynewami2
      tags:
         Name: MyNexusAMI
         Service: Nexus2
      device_mapping:
         - device_name: /dev/sdb1
           size: 100
           delete_on_termination: true
           volume_type: gp2
    register: instance
     
      
