--- # Loop playbook
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: add a list of users
     run_once: true
     delegate_to: 192.168.56.221
     user: name={{ item }} state=present
     with_items:
       - user1
       - user2
       - user3
